# Generated by Django 5.2.3 on 2025-06-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_adminuser_has_dashboard_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='has_dashboard_access',
            field=models.BooleanField(default=True),
        ),
    ]
