# Generated by Django 5.2.3 on 2025-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customadmin_delete_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadmin',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
