# Generated by Django 5.2.3 on 2025-07-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customadmin_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='can_manage_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
