# Generated by Django 5.2.3 on 2025-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_lead_message_lead_budget_lead_cms_lead_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='browser',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
