# Generated by Django 5.2.3 on 2025-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_supportticket_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, default='Not specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='cms',
            field=models.CharField(blank=True, default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='pages',
            field=models.CharField(blank=True, default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='payment',
            field=models.CharField(blank=True, default='Not specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(blank=True, default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='domain',
            field=models.CharField(default='Not specified', max_length=200),
            preserve_default=False,
        ),
    ]
