# Generated by Django 5.2.3 on 2025-06-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_lead_browser_lead_ip_lead_referrer_supportticket_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='requirement',
            field=models.TextField(blank=True),
        ),
    ]
