# Generated by Django 5.2.3 on 2025-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_lead_email_alter_lead_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='browser',
            field=models.TextField(blank=True, default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='payment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='referrer',
            field=models.TextField(blank=True, default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='browser',
            field=models.TextField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='domain',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='referrer',
            field=models.TextField(blank=True, default='Unknown'),
            preserve_default=False,
        ),
    ]
