# Generated by Django 5.2.3 on 2025-06-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_lead_browser_alter_lead_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='browser',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='browser',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
