# Generated by Django 5.2.3 on 2025-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_lead_browser_alter_supportticket_browser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='browser',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='referrer',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='browser',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='referrer',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
    ]
